/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppAboutRouteImport } from './routes/app/about'
import { Route as AppUsersRouteRouteImport } from './routes/app/users/route'
import { Route as AppTargetsRouteRouteImport } from './routes/app/targets/route'
import { Route as AppSessionsRouteRouteImport } from './routes/app/sessions/route'
import { Route as AppRolesRouteRouteImport } from './routes/app/roles/route'
import { Route as AppMaintenanceLogsRouteRouteImport } from './routes/app/maintenance-logs/route'
import { Route as AppGroupsRouteRouteImport } from './routes/app/groups/route'
import { Route as AppDummiesRouteRouteImport } from './routes/app/dummies/route'
import { Route as AppCyclesRouteRouteImport } from './routes/app/cycles/route'
import { Route as AppBranchesRouteRouteImport } from './routes/app/branches/route'
import { Route as AppTargetsIndexRouteImport } from './routes/app/targets/index'
import { Route as AppSessionsIndexRouteImport } from './routes/app/sessions/index'
import { Route as AppGroupsIndexRouteImport } from './routes/app/groups/index'
import { Route as AppDummiesIndexRouteImport } from './routes/app/dummies/index'
import { Route as AppCyclesIndexRouteImport } from './routes/app/cycles/index'
import { Route as AppBranchesIndexRouteImport } from './routes/app/branches/index'
import { Route as AppTargetsTargetIdRouteRouteImport } from './routes/app/targets/$targetId/route'
import { Route as AppBranchesBranchIdRouteRouteImport } from './routes/app/branches/$branchId/route'
import { Route as AppTargetsTargetIdIndexRouteImport } from './routes/app/targets/$targetId/index'
import { Route as AppBranchesBranchIdIndexRouteImport } from './routes/app/branches/$branchId/index'
import { Route as AppTargetsTargetIdMaintenanceLogsRouteImport } from './routes/app/targets/$targetId/maintenance-logs'
import { Route as AppBranchesBranchIdCyclesRouteImport } from './routes/app/branches/$branchId/cycles'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersRouteRoute = AppUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTargetsRouteRoute = AppTargetsRouteRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSessionsRouteRoute = AppSessionsRouteRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesRouteRoute = AppRolesRouteRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaintenanceLogsRouteRoute = AppMaintenanceLogsRouteRouteImport.update({
  id: '/maintenance-logs',
  path: '/maintenance-logs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGroupsRouteRoute = AppGroupsRouteRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDummiesRouteRoute = AppDummiesRouteRouteImport.update({
  id: '/dummies',
  path: '/dummies',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCyclesRouteRoute = AppCyclesRouteRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBranchesRouteRoute = AppBranchesRouteRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTargetsIndexRoute = AppTargetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTargetsRouteRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSessionsRouteRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGroupsRouteRoute,
} as any)
const AppDummiesIndexRoute = AppDummiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDummiesRouteRoute,
} as any)
const AppCyclesIndexRoute = AppCyclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCyclesRouteRoute,
} as any)
const AppBranchesIndexRoute = AppBranchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBranchesRouteRoute,
} as any)
const AppTargetsTargetIdRouteRoute = AppTargetsTargetIdRouteRouteImport.update({
  id: '/$targetId',
  path: '/$targetId',
  getParentRoute: () => AppTargetsRouteRoute,
} as any)
const AppBranchesBranchIdRouteRoute =
  AppBranchesBranchIdRouteRouteImport.update({
    id: '/$branchId',
    path: '/$branchId',
    getParentRoute: () => AppBranchesRouteRoute,
  } as any)
const AppTargetsTargetIdIndexRoute = AppTargetsTargetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTargetsTargetIdRouteRoute,
} as any)
const AppBranchesBranchIdIndexRoute =
  AppBranchesBranchIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppBranchesBranchIdRouteRoute,
  } as any)
const AppTargetsTargetIdMaintenanceLogsRoute =
  AppTargetsTargetIdMaintenanceLogsRouteImport.update({
    id: '/maintenance-logs',
    path: '/maintenance-logs',
    getParentRoute: () => AppTargetsTargetIdRouteRoute,
  } as any)
const AppBranchesBranchIdCyclesRoute =
  AppBranchesBranchIdCyclesRouteImport.update({
    id: '/cycles',
    path: '/cycles',
    getParentRoute: () => AppBranchesBranchIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/branches': typeof AppBranchesRouteRouteWithChildren
  '/app/cycles': typeof AppCyclesRouteRouteWithChildren
  '/app/dummies': typeof AppDummiesRouteRouteWithChildren
  '/app/groups': typeof AppGroupsRouteRouteWithChildren
  '/app/maintenance-logs': typeof AppMaintenanceLogsRouteRoute
  '/app/roles': typeof AppRolesRouteRoute
  '/app/sessions': typeof AppSessionsRouteRouteWithChildren
  '/app/targets': typeof AppTargetsRouteRouteWithChildren
  '/app/users': typeof AppUsersRouteRoute
  '/app/about': typeof AppAboutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/branches/$branchId': typeof AppBranchesBranchIdRouteRouteWithChildren
  '/app/targets/$targetId': typeof AppTargetsTargetIdRouteRouteWithChildren
  '/app/branches/': typeof AppBranchesIndexRoute
  '/app/cycles/': typeof AppCyclesIndexRoute
  '/app/dummies/': typeof AppDummiesIndexRoute
  '/app/groups/': typeof AppGroupsIndexRoute
  '/app/sessions/': typeof AppSessionsIndexRoute
  '/app/targets/': typeof AppTargetsIndexRoute
  '/app/branches/$branchId/cycles': typeof AppBranchesBranchIdCyclesRoute
  '/app/targets/$targetId/maintenance-logs': typeof AppTargetsTargetIdMaintenanceLogsRoute
  '/app/branches/$branchId/': typeof AppBranchesBranchIdIndexRoute
  '/app/targets/$targetId/': typeof AppTargetsTargetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/maintenance-logs': typeof AppMaintenanceLogsRouteRoute
  '/app/roles': typeof AppRolesRouteRoute
  '/app/users': typeof AppUsersRouteRoute
  '/app/about': typeof AppAboutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/branches': typeof AppBranchesIndexRoute
  '/app/cycles': typeof AppCyclesIndexRoute
  '/app/dummies': typeof AppDummiesIndexRoute
  '/app/groups': typeof AppGroupsIndexRoute
  '/app/sessions': typeof AppSessionsIndexRoute
  '/app/targets': typeof AppTargetsIndexRoute
  '/app/branches/$branchId/cycles': typeof AppBranchesBranchIdCyclesRoute
  '/app/targets/$targetId/maintenance-logs': typeof AppTargetsTargetIdMaintenanceLogsRoute
  '/app/branches/$branchId': typeof AppBranchesBranchIdIndexRoute
  '/app/targets/$targetId': typeof AppTargetsTargetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/branches': typeof AppBranchesRouteRouteWithChildren
  '/app/cycles': typeof AppCyclesRouteRouteWithChildren
  '/app/dummies': typeof AppDummiesRouteRouteWithChildren
  '/app/groups': typeof AppGroupsRouteRouteWithChildren
  '/app/maintenance-logs': typeof AppMaintenanceLogsRouteRoute
  '/app/roles': typeof AppRolesRouteRoute
  '/app/sessions': typeof AppSessionsRouteRouteWithChildren
  '/app/targets': typeof AppTargetsRouteRouteWithChildren
  '/app/users': typeof AppUsersRouteRoute
  '/app/about': typeof AppAboutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/branches/$branchId': typeof AppBranchesBranchIdRouteRouteWithChildren
  '/app/targets/$targetId': typeof AppTargetsTargetIdRouteRouteWithChildren
  '/app/branches/': typeof AppBranchesIndexRoute
  '/app/cycles/': typeof AppCyclesIndexRoute
  '/app/dummies/': typeof AppDummiesIndexRoute
  '/app/groups/': typeof AppGroupsIndexRoute
  '/app/sessions/': typeof AppSessionsIndexRoute
  '/app/targets/': typeof AppTargetsIndexRoute
  '/app/branches/$branchId/cycles': typeof AppBranchesBranchIdCyclesRoute
  '/app/targets/$targetId/maintenance-logs': typeof AppTargetsTargetIdMaintenanceLogsRoute
  '/app/branches/$branchId/': typeof AppBranchesBranchIdIndexRoute
  '/app/targets/$targetId/': typeof AppTargetsTargetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/branches'
    | '/app/cycles'
    | '/app/dummies'
    | '/app/groups'
    | '/app/maintenance-logs'
    | '/app/roles'
    | '/app/sessions'
    | '/app/targets'
    | '/app/users'
    | '/app/about'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/'
    | '/app/branches/$branchId'
    | '/app/targets/$targetId'
    | '/app/branches/'
    | '/app/cycles/'
    | '/app/dummies/'
    | '/app/groups/'
    | '/app/sessions/'
    | '/app/targets/'
    | '/app/branches/$branchId/cycles'
    | '/app/targets/$targetId/maintenance-logs'
    | '/app/branches/$branchId/'
    | '/app/targets/$targetId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/maintenance-logs'
    | '/app/roles'
    | '/app/users'
    | '/app/about'
    | '/app/dashboard'
    | '/app/settings'
    | '/app'
    | '/app/branches'
    | '/app/cycles'
    | '/app/dummies'
    | '/app/groups'
    | '/app/sessions'
    | '/app/targets'
    | '/app/branches/$branchId/cycles'
    | '/app/targets/$targetId/maintenance-logs'
    | '/app/branches/$branchId'
    | '/app/targets/$targetId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/branches'
    | '/app/cycles'
    | '/app/dummies'
    | '/app/groups'
    | '/app/maintenance-logs'
    | '/app/roles'
    | '/app/sessions'
    | '/app/targets'
    | '/app/users'
    | '/app/about'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/'
    | '/app/branches/$branchId'
    | '/app/targets/$targetId'
    | '/app/branches/'
    | '/app/cycles/'
    | '/app/dummies/'
    | '/app/groups/'
    | '/app/sessions/'
    | '/app/targets/'
    | '/app/branches/$branchId/cycles'
    | '/app/targets/$targetId/maintenance-logs'
    | '/app/branches/$branchId/'
    | '/app/targets/$targetId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/targets': {
      id: '/app/targets'
      path: '/targets'
      fullPath: '/app/targets'
      preLoaderRoute: typeof AppTargetsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sessions': {
      id: '/app/sessions'
      path: '/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AppSessionsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/maintenance-logs': {
      id: '/app/maintenance-logs'
      path: '/maintenance-logs'
      fullPath: '/app/maintenance-logs'
      preLoaderRoute: typeof AppMaintenanceLogsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/groups': {
      id: '/app/groups'
      path: '/groups'
      fullPath: '/app/groups'
      preLoaderRoute: typeof AppGroupsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dummies': {
      id: '/app/dummies'
      path: '/dummies'
      fullPath: '/app/dummies'
      preLoaderRoute: typeof AppDummiesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cycles': {
      id: '/app/cycles'
      path: '/cycles'
      fullPath: '/app/cycles'
      preLoaderRoute: typeof AppCyclesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/branches': {
      id: '/app/branches'
      path: '/branches'
      fullPath: '/app/branches'
      preLoaderRoute: typeof AppBranchesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/targets/': {
      id: '/app/targets/'
      path: '/'
      fullPath: '/app/targets/'
      preLoaderRoute: typeof AppTargetsIndexRouteImport
      parentRoute: typeof AppTargetsRouteRoute
    }
    '/app/sessions/': {
      id: '/app/sessions/'
      path: '/'
      fullPath: '/app/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppSessionsRouteRoute
    }
    '/app/groups/': {
      id: '/app/groups/'
      path: '/'
      fullPath: '/app/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppGroupsRouteRoute
    }
    '/app/dummies/': {
      id: '/app/dummies/'
      path: '/'
      fullPath: '/app/dummies/'
      preLoaderRoute: typeof AppDummiesIndexRouteImport
      parentRoute: typeof AppDummiesRouteRoute
    }
    '/app/cycles/': {
      id: '/app/cycles/'
      path: '/'
      fullPath: '/app/cycles/'
      preLoaderRoute: typeof AppCyclesIndexRouteImport
      parentRoute: typeof AppCyclesRouteRoute
    }
    '/app/branches/': {
      id: '/app/branches/'
      path: '/'
      fullPath: '/app/branches/'
      preLoaderRoute: typeof AppBranchesIndexRouteImport
      parentRoute: typeof AppBranchesRouteRoute
    }
    '/app/targets/$targetId': {
      id: '/app/targets/$targetId'
      path: '/$targetId'
      fullPath: '/app/targets/$targetId'
      preLoaderRoute: typeof AppTargetsTargetIdRouteRouteImport
      parentRoute: typeof AppTargetsRouteRoute
    }
    '/app/branches/$branchId': {
      id: '/app/branches/$branchId'
      path: '/$branchId'
      fullPath: '/app/branches/$branchId'
      preLoaderRoute: typeof AppBranchesBranchIdRouteRouteImport
      parentRoute: typeof AppBranchesRouteRoute
    }
    '/app/targets/$targetId/': {
      id: '/app/targets/$targetId/'
      path: '/'
      fullPath: '/app/targets/$targetId/'
      preLoaderRoute: typeof AppTargetsTargetIdIndexRouteImport
      parentRoute: typeof AppTargetsTargetIdRouteRoute
    }
    '/app/branches/$branchId/': {
      id: '/app/branches/$branchId/'
      path: '/'
      fullPath: '/app/branches/$branchId/'
      preLoaderRoute: typeof AppBranchesBranchIdIndexRouteImport
      parentRoute: typeof AppBranchesBranchIdRouteRoute
    }
    '/app/targets/$targetId/maintenance-logs': {
      id: '/app/targets/$targetId/maintenance-logs'
      path: '/maintenance-logs'
      fullPath: '/app/targets/$targetId/maintenance-logs'
      preLoaderRoute: typeof AppTargetsTargetIdMaintenanceLogsRouteImport
      parentRoute: typeof AppTargetsTargetIdRouteRoute
    }
    '/app/branches/$branchId/cycles': {
      id: '/app/branches/$branchId/cycles'
      path: '/cycles'
      fullPath: '/app/branches/$branchId/cycles'
      preLoaderRoute: typeof AppBranchesBranchIdCyclesRouteImport
      parentRoute: typeof AppBranchesBranchIdRouteRoute
    }
  }
}

interface AppBranchesBranchIdRouteRouteChildren {
  AppBranchesBranchIdCyclesRoute: typeof AppBranchesBranchIdCyclesRoute
  AppBranchesBranchIdIndexRoute: typeof AppBranchesBranchIdIndexRoute
}

const AppBranchesBranchIdRouteRouteChildren: AppBranchesBranchIdRouteRouteChildren =
  {
    AppBranchesBranchIdCyclesRoute: AppBranchesBranchIdCyclesRoute,
    AppBranchesBranchIdIndexRoute: AppBranchesBranchIdIndexRoute,
  }

const AppBranchesBranchIdRouteRouteWithChildren =
  AppBranchesBranchIdRouteRoute._addFileChildren(
    AppBranchesBranchIdRouteRouteChildren,
  )

interface AppBranchesRouteRouteChildren {
  AppBranchesBranchIdRouteRoute: typeof AppBranchesBranchIdRouteRouteWithChildren
  AppBranchesIndexRoute: typeof AppBranchesIndexRoute
}

const AppBranchesRouteRouteChildren: AppBranchesRouteRouteChildren = {
  AppBranchesBranchIdRouteRoute: AppBranchesBranchIdRouteRouteWithChildren,
  AppBranchesIndexRoute: AppBranchesIndexRoute,
}

const AppBranchesRouteRouteWithChildren =
  AppBranchesRouteRoute._addFileChildren(AppBranchesRouteRouteChildren)

interface AppCyclesRouteRouteChildren {
  AppCyclesIndexRoute: typeof AppCyclesIndexRoute
}

const AppCyclesRouteRouteChildren: AppCyclesRouteRouteChildren = {
  AppCyclesIndexRoute: AppCyclesIndexRoute,
}

const AppCyclesRouteRouteWithChildren = AppCyclesRouteRoute._addFileChildren(
  AppCyclesRouteRouteChildren,
)

interface AppDummiesRouteRouteChildren {
  AppDummiesIndexRoute: typeof AppDummiesIndexRoute
}

const AppDummiesRouteRouteChildren: AppDummiesRouteRouteChildren = {
  AppDummiesIndexRoute: AppDummiesIndexRoute,
}

const AppDummiesRouteRouteWithChildren = AppDummiesRouteRoute._addFileChildren(
  AppDummiesRouteRouteChildren,
)

interface AppGroupsRouteRouteChildren {
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
}

const AppGroupsRouteRouteChildren: AppGroupsRouteRouteChildren = {
  AppGroupsIndexRoute: AppGroupsIndexRoute,
}

const AppGroupsRouteRouteWithChildren = AppGroupsRouteRoute._addFileChildren(
  AppGroupsRouteRouteChildren,
)

interface AppSessionsRouteRouteChildren {
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
}

const AppSessionsRouteRouteChildren: AppSessionsRouteRouteChildren = {
  AppSessionsIndexRoute: AppSessionsIndexRoute,
}

const AppSessionsRouteRouteWithChildren =
  AppSessionsRouteRoute._addFileChildren(AppSessionsRouteRouteChildren)

interface AppTargetsTargetIdRouteRouteChildren {
  AppTargetsTargetIdMaintenanceLogsRoute: typeof AppTargetsTargetIdMaintenanceLogsRoute
  AppTargetsTargetIdIndexRoute: typeof AppTargetsTargetIdIndexRoute
}

const AppTargetsTargetIdRouteRouteChildren: AppTargetsTargetIdRouteRouteChildren =
  {
    AppTargetsTargetIdMaintenanceLogsRoute:
      AppTargetsTargetIdMaintenanceLogsRoute,
    AppTargetsTargetIdIndexRoute: AppTargetsTargetIdIndexRoute,
  }

const AppTargetsTargetIdRouteRouteWithChildren =
  AppTargetsTargetIdRouteRoute._addFileChildren(
    AppTargetsTargetIdRouteRouteChildren,
  )

interface AppTargetsRouteRouteChildren {
  AppTargetsTargetIdRouteRoute: typeof AppTargetsTargetIdRouteRouteWithChildren
  AppTargetsIndexRoute: typeof AppTargetsIndexRoute
}

const AppTargetsRouteRouteChildren: AppTargetsRouteRouteChildren = {
  AppTargetsTargetIdRouteRoute: AppTargetsTargetIdRouteRouteWithChildren,
  AppTargetsIndexRoute: AppTargetsIndexRoute,
}

const AppTargetsRouteRouteWithChildren = AppTargetsRouteRoute._addFileChildren(
  AppTargetsRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppBranchesRouteRoute: typeof AppBranchesRouteRouteWithChildren
  AppCyclesRouteRoute: typeof AppCyclesRouteRouteWithChildren
  AppDummiesRouteRoute: typeof AppDummiesRouteRouteWithChildren
  AppGroupsRouteRoute: typeof AppGroupsRouteRouteWithChildren
  AppMaintenanceLogsRouteRoute: typeof AppMaintenanceLogsRouteRoute
  AppRolesRouteRoute: typeof AppRolesRouteRoute
  AppSessionsRouteRoute: typeof AppSessionsRouteRouteWithChildren
  AppTargetsRouteRoute: typeof AppTargetsRouteRouteWithChildren
  AppUsersRouteRoute: typeof AppUsersRouteRoute
  AppAboutRoute: typeof AppAboutRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBranchesRouteRoute: AppBranchesRouteRouteWithChildren,
  AppCyclesRouteRoute: AppCyclesRouteRouteWithChildren,
  AppDummiesRouteRoute: AppDummiesRouteRouteWithChildren,
  AppGroupsRouteRoute: AppGroupsRouteRouteWithChildren,
  AppMaintenanceLogsRouteRoute: AppMaintenanceLogsRouteRoute,
  AppRolesRouteRoute: AppRolesRouteRoute,
  AppSessionsRouteRoute: AppSessionsRouteRouteWithChildren,
  AppTargetsRouteRoute: AppTargetsRouteRouteWithChildren,
  AppUsersRouteRoute: AppUsersRouteRoute,
  AppAboutRoute: AppAboutRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
